import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1761510824733 implements MigrationInterface {
    name = 'InitialSchema1761510824733'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`sugerencia\` (\`id\` int NOT NULL AUTO_INCREMENT, \`nombre\` varchar(255) NOT NULL, \`email\` varchar(255) NOT NULL, \`telefono\` varchar(255) NOT NULL, \`contenido\` text NOT NULL, \`fecha\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`role\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` enum ('SUPERUSER', 'ADMIN', 'PERSONAL_BOMBERIL', 'VOLUNTARIO', 'CITIZEN') NOT NULL, UNIQUE INDEX \`IDX_ae4578dcaed5adff96595e6166\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`messages\` (\`id\` int NOT NULL AUTO_INCREMENT, \`content\` text NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`isRead\` tinyint NOT NULL DEFAULT 0, \`sender_id\` int NULL, \`conversation_id\` int NULL, INDEX \`IDX_98c733d0e5a415f703e284adaf\` (\`conversation_id\`, \`sender_id\`, \`created_at\`), INDEX \`IDX_d585da3d991e15ae4a174e2882\` (\`sender_id\`, \`created_at\`), INDEX \`IDX_8584a1974e1ca95f4861d975ff\` (\`conversation_id\`, \`created_at\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`conversations\` (\`id\` int NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`is_group\` tinyint NOT NULL DEFAULT 0, \`group_name\` varchar(255) NULL, \`created_by\` int NULL, INDEX \`IDX_7018433f850e2836a7d9df1b9d\` (\`updated_at\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`users\` (\`id\` int NOT NULL AUTO_INCREMENT, \`username\` varchar(255) NOT NULL, \`email\` varchar(255) NOT NULL, \`password\` varchar(255) NOT NULL, UNIQUE INDEX \`IDX_fe0bb3f6520ee0469504521e71\` (\`username\`), UNIQUE INDEX \`IDX_97672ac88f789774dd47f7c8be\` (\`email\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`participaciones\` (\`id\` int NOT NULL AUTO_INCREMENT, \`actividad\` enum ('Entrenamiento', 'Emergencia', 'Simulacros') NOT NULL, \`fecha\` date NOT NULL, \`horaInicio\` time NOT NULL, \`horaFin\` time NOT NULL, \`descripcion\` text NOT NULL, \`ubicacion\` varchar(255) NOT NULL, \`estado\` varchar(255) NOT NULL DEFAULT 'pendiente', \`fechaRegistro\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`motivoRechazo\` text NULL, \`voluntarioId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`mantenimientos\` (\`created_by\` int NOT NULL, \`updated_by\` int NOT NULL, \`deleted_by\` int NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`id\` varchar(36) NOT NULL, \`vehiculo_id\` varchar(255) NOT NULL, \`estado\` enum ('pendiente', 'en_revision', 'completado') NOT NULL COMMENT 'Estado del ciclo de vida del mantenimiento' DEFAULT 'pendiente', \`tipo\` enum ('preventivo', 'correctivo') NOT NULL COMMENT 'Tipo de mantenimiento: preventivo o correctivo', \`fecha\` date NOT NULL, \`descripcion\` varchar(255) NOT NULL, \`kilometraje\` int NULL, \`tecnico\` varchar(255) NULL, \`costo\` decimal(10,2) NULL, \`observaciones\` text NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`vehiculos\` (\`created_by\` int NOT NULL, \`updated_by\` int NOT NULL, \`deleted_by\` int NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`id\` varchar(36) NOT NULL, \`placa\` varchar(50) NOT NULL, \`tipo\` enum ('camión sisterna', 'carro ambulancia', 'pickup utilitario', 'moto', 'atv', 'jet ski', 'lancha rescate', 'dron reconocimiento') NOT NULL COMMENT 'Tipo de vehículo de la flota', \`estado_inicial\` enum ('nuevo', 'usado') NOT NULL COMMENT 'Estado al momento de adquisición', \`estado_actual\` enum ('en servicio', 'malo', 'fuera de servicio', 'dado de baja') NOT NULL COMMENT 'Estado operacional actual', \`fecha_adquisicion\` date NOT NULL, \`kilometraje\` int UNSIGNED NOT NULL DEFAULT '0', \`observaciones\` text NULL, UNIQUE INDEX \`IDX_a9455f3a37d1d922a10f51664e\` (\`placa\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`noticias\` (\`id\` int NOT NULL AUTO_INCREMENT, \`titulo\` varchar(255) NOT NULL, \`descripcion\` text NOT NULL, \`url\` varchar(1000) NOT NULL, \`fecha\` varchar(255) NOT NULL, \`deletedAt\` datetime(6) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`material_educativo\` (\`id\` int NOT NULL AUTO_INCREMENT, \`titulo\` varchar(255) NOT NULL, \`descripcion\` varchar(255) NOT NULL, \`tipo\` varchar(255) NOT NULL, \`url\` varchar(255) NOT NULL, \`vistaPrevia\` varchar(255) NULL, \`area\` varchar(255) NULL, \`created_by\` int NOT NULL, \`updated_by\` int NOT NULL, \`deleted_by\` int NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`catalogo_equipo\` (\`id\` varchar(36) NOT NULL, \`nombre\` varchar(255) NOT NULL, \`tipo\` enum ('terrestre', 'marítimo') NOT NULL, UNIQUE INDEX \`IDX_cdc16bcf020eb2e118d50a4ca6\` (\`nombre\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`equipo_mantenimiento\` (\`id\` varchar(36) NOT NULL, \`equipoId\` varchar(255) NOT NULL, \`fecha\` date NOT NULL, \`descripcion\` varchar(300) NOT NULL, \`tecnico\` varchar(150) NOT NULL, \`costo\` decimal(12,2) NULL, \`observaciones\` text NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`equipo_bomberil\` (\`id\` varchar(36) NOT NULL, \`catalogoId\` varchar(255) NOT NULL, \`fechaAdquisicion\` date NOT NULL, \`estadoInicial\` varchar(20) NOT NULL, \`estadoActual\` enum ('disponible', 'en mantenimiento', 'dado de baja') NOT NULL DEFAULT 'disponible', \`numeroSerie\` varchar(120) NULL, \`fotoUrl\` varchar(300) NULL, \`cantidad\` int NOT NULL, \`reposicionSolicitada\` tinyint NOT NULL DEFAULT 0, \`motivoReposicion\` text NULL, \`observacionesReposicion\` text NULL, INDEX \`IDX_11a0ea22d6fd731271c678d06f\` (\`catalogoId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`equipo_mantenimiento_programado\` (\`id\` varchar(36) NOT NULL, \`equipoId\` varchar(255) NOT NULL, \`fechaProximoMantenimiento\` date NOT NULL, \`tecnico\` varchar(150) NOT NULL, \`tipo\` enum ('preventivo', 'correctivo', 'inspección') NOT NULL, \`prioridad\` enum ('baja', 'media', 'alta') NOT NULL, \`observaciones\` text NULL, \`estado\` varchar(20) NOT NULL DEFAULT 'pendiente', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`donantes\` (\`id\` int NOT NULL AUTO_INCREMENT, \`nombre\` varchar(255) NOT NULL, \`descripcion\` text NOT NULL, \`logo\` varchar(1000) NULL, \`url\` varchar(1000) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`password_reset_tokens\` (\`id\` int NOT NULL AUTO_INCREMENT, \`userId\` int NOT NULL, \`token\` varchar(64) NOT NULL, \`expiresAt\` datetime NOT NULL, \`consumedAt\` datetime NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_ab673f0e63eac966762155508e\` (\`token\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`reports\` (\`id\` varchar(36) NOT NULL, \`type\` enum ('fire', 'accident', 'rescue', 'other') NOT NULL, \`lat\` decimal(10,6) NOT NULL, \`lng\` decimal(10,6) NOT NULL, \`status\` enum ('pending', 'assigned', 'in_progress', 'resolved', 'cancelled') NOT NULL DEFAULT 'pending', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`emergency_reports\` (\`id\` int NOT NULL AUTO_INCREMENT, \`mobile_user_id\` int NOT NULL, \`type\` enum ('FIRE', 'MEDICAL', 'ACCIDENT', 'RESCUE', 'OTHER') NOT NULL, \`latitud\` decimal(10,7) NOT NULL, \`longitud\` decimal(10,7) NOT NULL, \`status\` enum ('PENDING', 'IN_PROGRESS', 'RESOLVED', 'CLOSED') NOT NULL DEFAULT 'PENDING', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`first_response_at\` timestamp NULL, \`resolved_at\` timestamp NULL, \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`closed_by\` int NULL, \`incident_details\` text NULL, \`recommendations\` text NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`mobile_users\` (\`id\` int NOT NULL AUTO_INCREMENT, \`deviceId\` varchar(255) NOT NULL, \`username\` varchar(255) NOT NULL, \`email\` varchar(255) NULL, \`password\` varchar(255) NULL, \`isAnonymous\` tinyint NOT NULL DEFAULT 1, \`deviceInfo\` json NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_6b3576602a3947d2f23cf19566\` (\`deviceId\`), UNIQUE INDEX \`IDX_4db2413b05b601c6a178fda555\` (\`username\`), UNIQUE INDEX \`IDX_c5fd69ff3b140b2c3ad83861b7\` (\`email\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`report_attachments\` (\`id\` int NOT NULL AUTO_INCREMENT, \`emergency_report_id\` int NOT NULL, \`file_name\` varchar(255) NOT NULL, \`file_url\` varchar(500) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`involved_persons\` (\`id\` int NOT NULL AUTO_INCREMENT, \`emergency_report_id\` int NOT NULL, \`full_name\` varchar(255) NOT NULL, \`role\` enum ('VICTIM', 'WITNESS', 'RESPONSIBLE', 'OTHER') NOT NULL, \`phone\` varchar(50) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`status_changes\` (\`id\` int NOT NULL AUTO_INCREMENT, \`emergency_report_id\` int NOT NULL, \`from_status\` enum ('PENDING', 'IN_PROGRESS', 'RESOLVED', 'CLOSED') NOT NULL, \`to_status\` enum ('PENDING', 'IN_PROGRESS', 'RESOLVED', 'CLOSED') NOT NULL, \`changed_by\` int NOT NULL, \`notes\` text NULL, \`changed_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`conversation_participants\` (\`conversation_id\` int NOT NULL, \`user_id\` int NOT NULL, INDEX \`IDX_1559e8a16b828f2e836a231280\` (\`conversation_id\`), INDEX \`IDX_377d4041a495b81ee1a85ae026\` (\`user_id\`), PRIMARY KEY (\`conversation_id\`, \`user_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`users_roles_role\` (\`usersId\` int NOT NULL, \`roleId\` int NOT NULL, INDEX \`IDX_3ea8bcae76ff0b74bcc1340af8\` (\`usersId\`), INDEX \`IDX_03c652226fd376f26b31503d40\` (\`roleId\`), PRIMARY KEY (\`usersId\`, \`roleId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`DROP INDEX \`IDX_ae4578dcaed5adff96595e6166\` ON \`role\``);
        await queryRunner.query(`ALTER TABLE \`role\` DROP COLUMN \`name\``);
        await queryRunner.query(`ALTER TABLE \`role\` ADD \`name\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`role\` ADD UNIQUE INDEX \`IDX_ae4578dcaed5adff96595e6166\` (\`name\`)`);
        await queryRunner.query(`ALTER TABLE \`messages\` ADD CONSTRAINT \`FK_22133395bd13b970ccd0c34ab22\` FOREIGN KEY (\`sender_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`messages\` ADD CONSTRAINT \`FK_3bc55a7c3f9ed54b520bb5cfe23\` FOREIGN KEY (\`conversation_id\`) REFERENCES \`conversations\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`participaciones\` ADD CONSTRAINT \`FK_db9cae9177cb20bdb159b7fba7e\` FOREIGN KEY (\`voluntarioId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`mantenimientos\` ADD CONSTRAINT \`FK_9275c776b02375196266c55400d\` FOREIGN KEY (\`created_by\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`mantenimientos\` ADD CONSTRAINT \`FK_c6bed2b5ccb9acbbf6b5522e79f\` FOREIGN KEY (\`updated_by\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`mantenimientos\` ADD CONSTRAINT \`FK_b2124e611dfbaf2d502d2e97f13\` FOREIGN KEY (\`deleted_by\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`mantenimientos\` ADD CONSTRAINT \`FK_348c9e54e5becfc1e5040702ae2\` FOREIGN KEY (\`vehiculo_id\`) REFERENCES \`vehiculos\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`vehiculos\` ADD CONSTRAINT \`FK_4f92722e579197b611a4c990ca9\` FOREIGN KEY (\`created_by\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`vehiculos\` ADD CONSTRAINT \`FK_c0d041b7a5cfef3b7ea4f96b7b2\` FOREIGN KEY (\`updated_by\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`vehiculos\` ADD CONSTRAINT \`FK_0ff017cf6e8d07e2857af74a6ff\` FOREIGN KEY (\`deleted_by\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`material_educativo\` ADD CONSTRAINT \`FK_42ce95279e9946bcb869817cfc1\` FOREIGN KEY (\`created_by\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`material_educativo\` ADD CONSTRAINT \`FK_7d776dc8711c652cbdbe11fca79\` FOREIGN KEY (\`updated_by\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`material_educativo\` ADD CONSTRAINT \`FK_2fdecffc98e716b6532865a79eb\` FOREIGN KEY (\`deleted_by\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`equipo_mantenimiento\` ADD CONSTRAINT \`FK_c79449019b9528202d53f885cd9\` FOREIGN KEY (\`equipoId\`) REFERENCES \`equipo_bomberil\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`equipo_bomberil\` ADD CONSTRAINT \`FK_11a0ea22d6fd731271c678d06f4\` FOREIGN KEY (\`catalogoId\`) REFERENCES \`catalogo_equipo\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`equipo_mantenimiento_programado\` ADD CONSTRAINT \`FK_2e5bfa70ba16aff351805f89a1f\` FOREIGN KEY (\`equipoId\`) REFERENCES \`equipo_bomberil\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`password_reset_tokens\` ADD CONSTRAINT \`FK_d6a19d4b4f6c62dcd29daa497e2\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`emergency_reports\` ADD CONSTRAINT \`FK_a2d84c91326670b76130d4ac9e9\` FOREIGN KEY (\`mobile_user_id\`) REFERENCES \`mobile_users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`emergency_reports\` ADD CONSTRAINT \`FK_e73e116ab865701792b1adf96e2\` FOREIGN KEY (\`closed_by\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`report_attachments\` ADD CONSTRAINT \`FK_ffd8c0e6f7dab11d9c2f13e521f\` FOREIGN KEY (\`emergency_report_id\`) REFERENCES \`emergency_reports\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`involved_persons\` ADD CONSTRAINT \`FK_7a01d365429e6379184ca1a5a7b\` FOREIGN KEY (\`emergency_report_id\`) REFERENCES \`emergency_reports\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`status_changes\` ADD CONSTRAINT \`FK_129222d6855cdc46e25f91d2a0f\` FOREIGN KEY (\`emergency_report_id\`) REFERENCES \`emergency_reports\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`status_changes\` ADD CONSTRAINT \`FK_e76dc80231e4965550ca5290fa5\` FOREIGN KEY (\`changed_by\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`conversation_participants\` ADD CONSTRAINT \`FK_1559e8a16b828f2e836a2312800\` FOREIGN KEY (\`conversation_id\`) REFERENCES \`conversations\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`conversation_participants\` ADD CONSTRAINT \`FK_377d4041a495b81ee1a85ae026f\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users_roles_role\` ADD CONSTRAINT \`FK_3ea8bcae76ff0b74bcc1340af86\` FOREIGN KEY (\`usersId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`users_roles_role\` ADD CONSTRAINT \`FK_03c652226fd376f26b31503d40c\` FOREIGN KEY (\`roleId\`) REFERENCES \`role\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`users_roles_role\` DROP FOREIGN KEY \`FK_03c652226fd376f26b31503d40c\``);
        await queryRunner.query(`ALTER TABLE \`users_roles_role\` DROP FOREIGN KEY \`FK_3ea8bcae76ff0b74bcc1340af86\``);
        await queryRunner.query(`ALTER TABLE \`conversation_participants\` DROP FOREIGN KEY \`FK_377d4041a495b81ee1a85ae026f\``);
        await queryRunner.query(`ALTER TABLE \`conversation_participants\` DROP FOREIGN KEY \`FK_1559e8a16b828f2e836a2312800\``);
        await queryRunner.query(`ALTER TABLE \`status_changes\` DROP FOREIGN KEY \`FK_e76dc80231e4965550ca5290fa5\``);
        await queryRunner.query(`ALTER TABLE \`status_changes\` DROP FOREIGN KEY \`FK_129222d6855cdc46e25f91d2a0f\``);
        await queryRunner.query(`ALTER TABLE \`involved_persons\` DROP FOREIGN KEY \`FK_7a01d365429e6379184ca1a5a7b\``);
        await queryRunner.query(`ALTER TABLE \`report_attachments\` DROP FOREIGN KEY \`FK_ffd8c0e6f7dab11d9c2f13e521f\``);
        await queryRunner.query(`ALTER TABLE \`emergency_reports\` DROP FOREIGN KEY \`FK_e73e116ab865701792b1adf96e2\``);
        await queryRunner.query(`ALTER TABLE \`emergency_reports\` DROP FOREIGN KEY \`FK_a2d84c91326670b76130d4ac9e9\``);
        await queryRunner.query(`ALTER TABLE \`password_reset_tokens\` DROP FOREIGN KEY \`FK_d6a19d4b4f6c62dcd29daa497e2\``);
        await queryRunner.query(`ALTER TABLE \`equipo_mantenimiento_programado\` DROP FOREIGN KEY \`FK_2e5bfa70ba16aff351805f89a1f\``);
        await queryRunner.query(`ALTER TABLE \`equipo_bomberil\` DROP FOREIGN KEY \`FK_11a0ea22d6fd731271c678d06f4\``);
        await queryRunner.query(`ALTER TABLE \`equipo_mantenimiento\` DROP FOREIGN KEY \`FK_c79449019b9528202d53f885cd9\``);
        await queryRunner.query(`ALTER TABLE \`material_educativo\` DROP FOREIGN KEY \`FK_2fdecffc98e716b6532865a79eb\``);
        await queryRunner.query(`ALTER TABLE \`material_educativo\` DROP FOREIGN KEY \`FK_7d776dc8711c652cbdbe11fca79\``);
        await queryRunner.query(`ALTER TABLE \`material_educativo\` DROP FOREIGN KEY \`FK_42ce95279e9946bcb869817cfc1\``);
        await queryRunner.query(`ALTER TABLE \`vehiculos\` DROP FOREIGN KEY \`FK_0ff017cf6e8d07e2857af74a6ff\``);
        await queryRunner.query(`ALTER TABLE \`vehiculos\` DROP FOREIGN KEY \`FK_c0d041b7a5cfef3b7ea4f96b7b2\``);
        await queryRunner.query(`ALTER TABLE \`vehiculos\` DROP FOREIGN KEY \`FK_4f92722e579197b611a4c990ca9\``);
        await queryRunner.query(`ALTER TABLE \`mantenimientos\` DROP FOREIGN KEY \`FK_348c9e54e5becfc1e5040702ae2\``);
        await queryRunner.query(`ALTER TABLE \`mantenimientos\` DROP FOREIGN KEY \`FK_b2124e611dfbaf2d502d2e97f13\``);
        await queryRunner.query(`ALTER TABLE \`mantenimientos\` DROP FOREIGN KEY \`FK_c6bed2b5ccb9acbbf6b5522e79f\``);
        await queryRunner.query(`ALTER TABLE \`mantenimientos\` DROP FOREIGN KEY \`FK_9275c776b02375196266c55400d\``);
        await queryRunner.query(`ALTER TABLE \`participaciones\` DROP FOREIGN KEY \`FK_db9cae9177cb20bdb159b7fba7e\``);
        await queryRunner.query(`ALTER TABLE \`messages\` DROP FOREIGN KEY \`FK_3bc55a7c3f9ed54b520bb5cfe23\``);
        await queryRunner.query(`ALTER TABLE \`messages\` DROP FOREIGN KEY \`FK_22133395bd13b970ccd0c34ab22\``);
        await queryRunner.query(`ALTER TABLE \`role\` DROP INDEX \`IDX_ae4578dcaed5adff96595e6166\``);
        await queryRunner.query(`ALTER TABLE \`role\` DROP COLUMN \`name\``);
        await queryRunner.query(`ALTER TABLE \`role\` ADD \`name\` enum ('SUPERUSER', 'ADMIN', 'PERSONAL_BOMBERIL', 'VOLUNTARIO', 'CITIZEN') NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_ae4578dcaed5adff96595e6166\` ON \`role\` (\`name\`)`);
        await queryRunner.query(`DROP INDEX \`IDX_03c652226fd376f26b31503d40\` ON \`users_roles_role\``);
        await queryRunner.query(`DROP INDEX \`IDX_3ea8bcae76ff0b74bcc1340af8\` ON \`users_roles_role\``);
        await queryRunner.query(`DROP TABLE \`users_roles_role\``);
        await queryRunner.query(`DROP INDEX \`IDX_377d4041a495b81ee1a85ae026\` ON \`conversation_participants\``);
        await queryRunner.query(`DROP INDEX \`IDX_1559e8a16b828f2e836a231280\` ON \`conversation_participants\``);
        await queryRunner.query(`DROP TABLE \`conversation_participants\``);
        await queryRunner.query(`DROP TABLE \`status_changes\``);
        await queryRunner.query(`DROP TABLE \`involved_persons\``);
        await queryRunner.query(`DROP TABLE \`report_attachments\``);
        await queryRunner.query(`DROP INDEX \`IDX_c5fd69ff3b140b2c3ad83861b7\` ON \`mobile_users\``);
        await queryRunner.query(`DROP INDEX \`IDX_4db2413b05b601c6a178fda555\` ON \`mobile_users\``);
        await queryRunner.query(`DROP INDEX \`IDX_6b3576602a3947d2f23cf19566\` ON \`mobile_users\``);
        await queryRunner.query(`DROP TABLE \`mobile_users\``);
        await queryRunner.query(`DROP TABLE \`emergency_reports\``);
        await queryRunner.query(`DROP TABLE \`reports\``);
        await queryRunner.query(`DROP INDEX \`IDX_ab673f0e63eac966762155508e\` ON \`password_reset_tokens\``);
        await queryRunner.query(`DROP TABLE \`password_reset_tokens\``);
        await queryRunner.query(`DROP TABLE \`donantes\``);
        await queryRunner.query(`DROP TABLE \`equipo_mantenimiento_programado\``);
        await queryRunner.query(`DROP INDEX \`IDX_11a0ea22d6fd731271c678d06f\` ON \`equipo_bomberil\``);
        await queryRunner.query(`DROP TABLE \`equipo_bomberil\``);
        await queryRunner.query(`DROP TABLE \`equipo_mantenimiento\``);
        await queryRunner.query(`DROP INDEX \`IDX_cdc16bcf020eb2e118d50a4ca6\` ON \`catalogo_equipo\``);
        await queryRunner.query(`DROP TABLE \`catalogo_equipo\``);
        await queryRunner.query(`DROP TABLE \`material_educativo\``);
        await queryRunner.query(`DROP TABLE \`noticias\``);
        await queryRunner.query(`DROP INDEX \`IDX_a9455f3a37d1d922a10f51664e\` ON \`vehiculos\``);
        await queryRunner.query(`DROP TABLE \`vehiculos\``);
        await queryRunner.query(`DROP TABLE \`mantenimientos\``);
        await queryRunner.query(`DROP TABLE \`participaciones\``);
        await queryRunner.query(`DROP INDEX \`IDX_97672ac88f789774dd47f7c8be\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_fe0bb3f6520ee0469504521e71\` ON \`users\``);
        await queryRunner.query(`DROP TABLE \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_7018433f850e2836a7d9df1b9d\` ON \`conversations\``);
        await queryRunner.query(`DROP TABLE \`conversations\``);
        await queryRunner.query(`DROP INDEX \`IDX_8584a1974e1ca95f4861d975ff\` ON \`messages\``);
        await queryRunner.query(`DROP INDEX \`IDX_d585da3d991e15ae4a174e2882\` ON \`messages\``);
        await queryRunner.query(`DROP INDEX \`IDX_98c733d0e5a415f703e284adaf\` ON \`messages\``);
        await queryRunner.query(`DROP TABLE \`messages\``);
        await queryRunner.query(`DROP INDEX \`IDX_ae4578dcaed5adff96595e6166\` ON \`role\``);
        await queryRunner.query(`DROP TABLE \`role\``);
        await queryRunner.query(`DROP TABLE \`sugerencia\``);
    }

}
